from core.exceptions.base import CoreError


class CategoryCantBeItsOwnParent(CoreError):
    pass
